### ISSUE TITLE
Запуск скрипта на рабочем сервере

### ISSUE THREAD

**Issue by kulaginds** [FaustVlll/vkAPI#1]
Доброго времени суток.
Ув. разработчики, пробовали ли вы тестировать этот скрипт на рабочем сервере, а не на локалхосте?
Я тестировал на локалке - все отлично работает; тестировал на внешнем сервере - ВКонтакте API возвращает пустой ответ на любой запрос.

**Comment by Doctrs** [comment]
После написания статьи (и, соответственно, скрипта) он, наверное, еще месяц работал на сервере. После этого не тестировал. 
Как вариант - ошибка из-за старой версия curl, но если вы говорите что вообще на любой запрос приходит пустой ответ, то я даже не представляю что может быть. Хотя возможно что все таки проблема с curl, потому что контакт в любом случае должен возвращать хотя бы код ошибки.

**Comment by kulaginds** [comment]
Сейчас попробовал на другом сервере, все правильно сработало.

**Comment by Doctrs** [comment]
В скрипте используются только php и curl - значит на том сервере был косяк каком то из этих 2х компонентов.

**Comment by kulaginds** [comment]
Спасибо!

**Comment by LennyLip** [comment]
В документации написано, что нельзя использовать Implicit flow для сервера. Никого не банили по этому поводу?
